name: Upgrade helm chart
on:
  workflow_dispatch:
jobs:
  Update:
    runs-on: ogechibogu/docker-helm:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: check compare chart versions 
        run: |
          helm repo add gcs-repo gs://chart-museum-007/charts 
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo list
      - name: Update versions
        run: |
          echo "charts are up to date"
     
    

