name: Upgrade helm chart
on:
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    container: ogechibogu/docker-helm:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: install dependencies 
        run: |
          helm plugin install https://github.com/hayorov/helm-gcs.git --version 0.4.0
          helm plugin update gcs
          SECRET_JSON=${{ secrets.GCLOUD_ACCESS_KEY }} 
          echo $SECRET_JSON
          ls -a /root/.config/gcloud
          #/root/.config/gcloud/application_default_credentials.json
          #gcloud auth activate-service-account --key-file /root/.config/gcloud/application_default_credentials.json
          #gcloud config set project $GCP_PROJECT_ID
          
      - name: check compare chart versions 
        run: |
          echo "git hub actions is the way"
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add gcs-repo gs://chart-museum-007/charts
          gcloud auth list
      - name: Update versions
        run: |
          echo "charts are up to date"
     
    

