name: Upgrade helm chart
on:
  workflow_dispatch:
jobs:
  Update:
    runs-on: ubuntu-latest
    container: ogechibogu/docker-helm:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: check compare chart versions 
        run: |
          echo "git hub actions is the way"
          helm repo add bitnami https://charts.bitnami.com/bitnami
          gcloud auth list
      - name: Update versions
        run: |
          echo "charts are up to date"
     
    

